
-- Add audit column for applied discount
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS applied_discount_pct numeric NOT NULL DEFAULT 0;

-- Seed warranty templates (idempotent by name)
INSERT INTO public.warranty_templates (name, months, intro_text, conditions, exclusions, default_for_category, active)
SELECT * FROM (VALUES
  ('Motor e Componentes Internos', 6,
    'A garantia cobre defeitos de fabricação em motor e componentes internos pelo prazo indicado, contados a partir da emissão da nota fiscal.',
    ARRAY['Instalação por profissional qualificado','Uso de lubrificantes e fluidos recomendados pelo fabricante','Apresentação da nota fiscal de venda','Manutenção preventiva conforme plano da máquina'],
    ARRAY['Danos por uso indevido, sobrecarga ou negligência','Avarias por contaminação de combustível, óleo ou água','Modificações ou reparos por terceiros não autorizados','Desgaste natural por uso prolongado'],
    'Motor', true),
  ('Sistema Hidráulico', 3,
    'Garantia para componentes hidráulicos (bombas, válvulas, cilindros, comandos) contra defeitos de fabricação.',
    ARRAY['Uso de óleo hidráulico recomendado e filtros originais','Instalação por profissional qualificado','Sistema sangrado e pressurizado conforme especificação'],
    ARRAY['Contaminação por partículas, água ou óleo inadequado','Operação acima da pressão de trabalho','Vazamentos por mau aperto na instalação','Desgaste natural de vedações'],
    'Hidráulic', true),
  ('Sistema Elétrico', 3,
    'Garantia para componentes elétricos (alternadores, motores de partida, sensores, chicotes) contra defeitos de fabricação.',
    ARRAY['Instalação por eletricista qualificado','Sistema com aterramento correto','Bateria em bom estado e tensão correta'],
    ARRAY['Queima por curto-circuito ou sobretensão','Danos por umidade ou imersão','Modificações no chicote ou conexões','Falta de fusíveis adequados'],
    'Elétric', true),
  ('Material Rodante', 3,
    'Garantia para componentes do material rodante (sapatas, elos, roletes, rodas-guia, coroas) contra defeitos de fabricação.',
    ARRAY['Tensão da esteira ajustada conforme manual','Operação em terreno compatível com a aplicação da máquina','Inspeção periódica de desgaste'],
    ARRAY['Desgaste por abrasão e uso normal','Operação em terreno rochoso sem proteção adequada','Tensão incorreta da esteira','Choques e impactos por má operação'],
    'Rodante', true),
  ('Filtros e Consumíveis', 0,
    'Itens de consumo e desgaste programado não possuem garantia de durabilidade, apenas garantia contra defeitos visíveis de fabricação no ato da entrega.',
    ARRAY['Inspeção no ato do recebimento','Troca conforme plano de manutenção'],
    ARRAY['Saturação por uso','Desgaste natural','Contaminação do fluido filtrado'],
    'Filtro', true),
  ('Pneus', 6,
    'Garantia de fabricação de pneus contra defeitos estruturais (separação de lonas, bolhas, defeitos de talão), conforme política do fabricante.',
    ARRAY['Calibragem conforme pressão indicada','Alinhamento e balanceamento periódicos','Operação dentro da capacidade de carga'],
    ARRAY['Cortes, perfurações e impactos','Desgaste por uso','Operação com pressão incorreta','Sobrecarga da máquina'],
    'Pneu', true),
  ('Peça Recondicionada', 3,
    'Peça recondicionada com garantia limitada contra defeitos de funcionamento, após instalação correta por profissional qualificado.',
    ARRAY['Instalação por profissional qualificado','Teste de funcionamento documentado','Uso de fluidos e filtros novos no sistema'],
    ARRAY['Componentes externos sujeitos a desgaste','Danos por má instalação','Reutilização de vedações ou parafusos antigos','Operação fora das especificações originais'],
    'Recondicion', true),
  ('Peça Usada', 1,
    'Peça usada vendida no estado em que se encontra. Garantia limitada de 30 dias contra defeito oculto não identificado no momento da venda.',
    ARRAY['Inspeção e teste pelo comprador antes da instalação','Comunicação de qualquer defeito em até 30 dias'],
    ARRAY['Desgaste visível no ato da compra','Danos após instalação','Componentes secundários (vedações, parafusos, mangueiras)','Diferença de desempenho em relação a peça nova'],
    'Usad', true),
  ('Acessórios e Cabine', 6,
    'Garantia para acessórios, vidros, bancos, retrovisores e componentes de cabine contra defeitos de fabricação.',
    ARRAY['Instalação por profissional qualificado','Uso conforme finalidade original'],
    ARRAY['Quebras por impacto','Riscos e desgaste estético','Modificações no produto'],
    'Cabine', true),
  ('Padrão Geral', 3,
    'Garantia padrão de fabricação contra defeitos no produto pelo prazo indicado, contado a partir da emissão da nota fiscal.',
    ARRAY['Instalação por profissional qualificado','Apresentação da nota fiscal','Uso conforme especificações do fabricante'],
    ARRAY['Uso indevido, negligência ou imperícia','Modificações por terceiros','Desgaste natural por uso'],
    NULL, true)
) AS v(name, months, intro_text, conditions, exclusions, default_for_category, active)
WHERE NOT EXISTS (SELECT 1 FROM public.warranty_templates w WHERE w.name = v.name);
